image: drecom/centos-ruby:latest

before_script:
  - ./gitlab-ci/setup.sh

variables:
  RAILS_ENV: 'test'

stages:
  - misc
  - test

.rspec-default: &rspec-default
  stage: test
  script:
    - bundle exec rubocop
    - bundle exec rspec
  services:
    - mysql:5.7

.use-ruby2_6: &use-ruby2_6
  image: drecom/centos-ruby:2.6.7

.use-ruby2_7: &use-ruby2_7
  image: drecom/centos-ruby:2.7.3

.use-ruby3_0: &use-ruby3_0
  image: drecom/centos-ruby:3.0.2

.use-rails6_0: &use-rails6_0
  variables:
    BUNDLE_GEMFILE: "spec/gemfiles/rails6_0.gemfile"
    RAILS_VERSION: '6.0'

.use-rails6_1: &use-rails6_1
  variables:
    BUNDLE_GEMFILE: "spec/gemfiles/rails6_1.gemfile"
    RAILS_VERSION: '6.1'

.use-rails7_0: &use-rails7_0
  variables:
    BUNDLE_GEMFILE: "spec/gemfiles/rails7_0.gemfile"
    RAILS_VERSION: '7.0'

ruby2.6-rails6.0:
    <<: *rspec-default
    <<: *use-ruby2_6
    <<: *use-rails6_0

ruby2.6-rails6.1:
    <<: *rspec-default
    <<: *use-ruby2_6
    <<: *use-rails6_1

ruby2.7-rails6.0:
    <<: *rspec-default
    <<: *use-ruby2_7
    <<: *use-rails6_0

ruby2.7-rails6.1:
    <<: *rspec-default
    <<: *use-ruby2_7
    <<: *use-rails6_1

ruby2.7-rails7.0:
    <<: *rspec-default
    <<: *use-ruby2_7
    <<: *use-rails7_0

ruby3.0-rails6.0:
    <<: *rspec-default
    <<: *use-ruby3_0
    <<: *use-rails6_0

ruby3.0-rails6.1:
    <<: *rspec-default
    <<: *use-ruby3_0
    <<: *use-rails6_1

ruby3.0-rails7.0:
    <<: *rspec-default
    <<: *use-ruby3_0
    <<: *use-rails7_0

##################################################
########## Assign MergeRequest Job ###############
##################################################

.assign_mr: &assign_mr
  stage: misc
  image: alpine:3.18
  before_script:
    - echo "Start before_script | `date`"
    - apk --update add --no-cache curl bash git openssh-client> /dev/null
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p -m 0700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - git clone ssh://git@git.drecom.jp:10022/diet/diet-ci-scripts.git /diet-ci-scripts
  script:
    - /diet-ci-scripts/assign-mr.sh

assign-mr-to-random-user:
  <<: *assign_mr
  needs: []
  rules:
    - if: $CI_MERGE_REQUEST_IID
      when: manual
      allow_failure: true
